2023-01-17 17:44:35,547: [11] m.main:INFO: Registered plugins: IntrospectionAPIPlugin, <class 'manticore.ethereum.plugins.SkipRevertBasicBlocks'>, <class 'manticore.ethereum.plugins.FilterFunctions'>
2023-01-17 17:44:35,547: [11] m.main:INFO: Beginning analysis
2023-01-17 17:44:35,552: [11] m.e.manticore:INFO: Starting symbolic create contract
2023-01-17 17:44:37,440: [11] m.e.manticore:INFO: Starting symbolic transaction: 0
2023-01-17 17:44:50,992: [11] m.e.manticore:INFO: Found a concrete globalsha3 b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' -> 73138091548938366139099779971772605061518111956507126412222883840269740007539
2023-01-17 17:44:51,558: [11] m.c.worker:ERROR: Exception in state 7: ManticoreError('Forking on unfeasible constraint set')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 137, in run
    current_state.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/ethereum/state.py", line 8, in execute
    return self._platform.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 3106, in execute
    self.current_vm.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 1322, in execute
    raise Concretize("Symbolic PC", expression=expression, setstate=setstate, policy="ALL")
manticore.core.state.Concretize

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 158, in run
    m._fork(current_state, exc.expression, exc.policy, exc.setstate, exc.values)
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/manticore.py", line 518, in _fork
    raise ManticoreError("Forking on unfeasible constraint set")
manticore.exceptions.ManticoreError: Forking on unfeasible constraint set
 
2023-01-17 17:45:07,010: [11] m.e.manticore:INFO: 4 alive states, 1 terminated states
2023-01-17 17:45:07,726: [11] m.e.manticore:INFO: Starting symbolic transaction: 1
2023-01-17 17:46:13,926: [11] m.c.worker:ERROR: Exception in state 0: ManticoreError('Forking on unfeasible constraint set')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 137, in run
    current_state.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/ethereum/state.py", line 8, in execute
    return self._platform.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 3106, in execute
    self.current_vm.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 1322, in execute
    raise Concretize("Symbolic PC", expression=expression, setstate=setstate, policy="ALL")
manticore.core.state.Concretize

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 158, in run
    m._fork(current_state, exc.expression, exc.policy, exc.setstate, exc.values)
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/manticore.py", line 518, in _fork
    raise ManticoreError("Forking on unfeasible constraint set")
manticore.exceptions.ManticoreError: Forking on unfeasible constraint set
 
2023-01-17 17:46:16,946: [11] m.c.worker:ERROR: Exception in state 10: ManticoreError('Forking on unfeasible constraint set')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 137, in run
    current_state.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/ethereum/state.py", line 8, in execute
    return self._platform.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 3106, in execute
    self.current_vm.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 1322, in execute
    raise Concretize("Symbolic PC", expression=expression, setstate=setstate, policy="ALL")
manticore.core.state.Concretize

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 158, in run
    m._fork(current_state, exc.expression, exc.policy, exc.setstate, exc.values)
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/manticore.py", line 518, in _fork
    raise ManticoreError("Forking on unfeasible constraint set")
manticore.exceptions.ManticoreError: Forking on unfeasible constraint set
 
2023-01-17 17:46:23,405: [11] m.c.worker:ERROR: Exception in state 2: ManticoreError('Forking on unfeasible constraint set')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 137, in run
    current_state.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/ethereum/state.py", line 8, in execute
    return self._platform.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 3106, in execute
    self.current_vm.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 1322, in execute
    raise Concretize("Symbolic PC", expression=expression, setstate=setstate, policy="ALL")
manticore.core.state.Concretize

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 158, in run
    m._fork(current_state, exc.expression, exc.policy, exc.setstate, exc.values)
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/manticore.py", line 518, in _fork
    raise ManticoreError("Forking on unfeasible constraint set")
manticore.exceptions.ManticoreError: Forking on unfeasible constraint set
 
2023-01-17 17:46:32,097: [11] m.c.worker:ERROR: Exception in state 7: ManticoreError('Forking on unfeasible constraint set')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 137, in run
    current_state.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/ethereum/state.py", line 8, in execute
    return self._platform.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 3106, in execute
    self.current_vm.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 1322, in execute
    raise Concretize("Symbolic PC", expression=expression, setstate=setstate, policy="ALL")
manticore.core.state.Concretize

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 158, in run
    m._fork(current_state, exc.expression, exc.policy, exc.setstate, exc.values)
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/manticore.py", line 518, in _fork
    raise ManticoreError("Forking on unfeasible constraint set")
manticore.exceptions.ManticoreError: Forking on unfeasible constraint set
 
2023-01-17 17:47:36,605: [11] m.e.manticore:INFO: 16 alive states, 1 terminated states
2023-01-17 17:47:37,634: [107] m.c.manticore:INFO: Generated testcase No. 0 - STOP(3 txs)
2023-01-17 17:47:37,635: [107] m.c.plugin:WARNING: Caught will_solve in state None, but failed to capture its initialization
2023-01-17 17:47:37,655: [99] m.c.manticore:INFO: Generated testcase No. 2 - STOP(3 txs)
2023-01-17 17:47:37,657: [99] m.c.plugin:WARNING: Caught will_solve in state None, but failed to capture its initialization
2023-01-17 17:47:37,659: [101] m.c.manticore:INFO: Generated testcase No. 1 - STOP(3 txs)
2023-01-17 17:47:37,661: [101] m.c.plugin:WARNING: Caught will_solve in state None, but failed to capture its initialization
2023-01-17 17:47:37,662: [104] m.c.manticore:INFO: Generated testcase No. 3 - STOP(3 txs)
2023-01-17 17:47:37,664: [104] m.c.plugin:WARNING: Caught will_solve in state None, but failed to capture its initialization
2023-01-17 17:47:38,425: [100] m.c.plugin:WARNING: Caught will_solve in state None, but failed to capture its initialization
2023-01-17 17:47:38,436: [105] m.c.plugin:WARNING: Caught will_solve in state None, but failed to capture its initialization
2023-01-17 17:47:38,572: [109] m.c.plugin:WARNING: Caught will_solve in state None, but failed to capture its initialization
2023-01-17 17:47:39,316: [100] m.c.manticore:INFO: Generated testcase No. 4 - STOP(3 txs)
2023-01-17 17:47:39,371: [105] m.c.manticore:INFO: Generated testcase No. 5 - STOP(3 txs)
2023-01-17 17:47:39,560: [109] m.c.manticore:INFO: Generated testcase No. 6 - RETURN(3 txs)
2023-01-17 17:47:39,795: [102] m.c.plugin:WARNING: Caught will_solve in state None, but failed to capture its initialization
2023-01-17 17:47:40,487: [98] m.c.plugin:WARNING: Caught will_solve in state None, but failed to capture its initialization
2023-01-17 17:47:40,509: [108] m.c.plugin:WARNING: Caught will_solve in state None, but failed to capture its initialization
2023-01-17 17:47:41,727: [102] m.c.manticore:INFO: Generated testcase No. 7 - STOP(3 txs)
2023-01-17 17:47:42,243: [106] m.c.plugin:WARNING: Caught will_solve in state None, but failed to capture its initialization
2023-01-17 17:47:42,387: [107] m.c.manticore:INFO: Generated testcase No. 8 - RETURN(3 txs)
2023-01-17 17:47:42,828: [98] m.c.manticore:INFO: Generated testcase No. 9 - STOP(3 txs)
2023-01-17 17:47:43,213: [108] m.c.manticore:INFO: Generated testcase No. 10 - RETURN(3 txs)
2023-01-17 17:47:44,980: [105] m.c.manticore:INFO: Generated testcase No. 11 - STOP(3 txs)
2023-01-17 17:47:45,202: [99] m.c.manticore:INFO: Generated testcase No. 12 - STOP(3 txs)
2023-01-17 17:47:47,226: [106] m.c.manticore:INFO: Generated testcase No. 13 - RETURN(3 txs)
2023-01-17 17:47:48,624: [104] m.c.manticore:INFO: Generated testcase No. 14 - STOP(3 txs)
2023-01-17 17:47:54,196: [101] m.c.manticore:INFO: Generated testcase No. 15 - STOP(3 txs)
2023-01-17 17:48:07,066: [11] m.c.plugin:WARNING: Caught will_solve in state None, but failed to capture its initialization
2023-01-17 17:48:47,453: [11] m.c.manticore:INFO: Results in /mcore_9rsbq49b
2023-01-17 17:48:47,454: [11] m.c.manticore:INFO: Total time: 219.2943639755249
