2022-06-02 13:11:38,096: [14] m.main:INFO: Registered plugins: IntrospectionAPIPlugin, <class 'manticore.ethereum.plugins.SkipRevertBasicBlocks'>, <class 'manticore.ethereum.plugins.FilterFunctions'>
2022-06-02 13:11:38,096: [14] m.main:INFO: Beginning analysis
2022-06-02 13:11:38,100: [14] m.e.manticore:INFO: Starting symbolic create contract
2022-06-02 13:11:38,806: [14] m.e.manticore:INFO: Starting symbolic transaction: 0
2022-06-02 13:11:46,553: [14] m.e.manticore:INFO: 7 alive states, 2 terminated states
2022-06-02 13:11:46,977: [91] m.c.manticore:INFO: Generated testcase No. 0 - STOP(2 txs)
2022-06-02 13:11:46,979: [89] m.c.manticore:INFO: Generated testcase No. 1 - STOP(2 txs)
2022-06-02 13:11:46,981: [89] m.c.plugin:WARNING: Caught will_solve in state None, but failed to capture its initialization
2022-06-02 13:11:46,979: [91] m.c.plugin:WARNING: Caught will_solve in state None, but failed to capture its initialization
2022-06-02 13:11:46,998: [86] m.c.manticore:INFO: Generated testcase No. 2 - STOP(2 txs)
2022-06-02 13:11:47,000: [86] m.c.plugin:WARNING: Caught will_solve in state None, but failed to capture its initialization
2022-06-02 13:11:47,001: [90] m.c.manticore:INFO: Generated testcase No. 3 - STOP(2 txs)
2022-06-02 13:11:47,003: [90] m.c.plugin:WARNING: Caught will_solve in state None, but failed to capture its initialization
2022-06-02 13:11:47,011: [87] m.c.manticore:INFO: Generated testcase No. 4 - STOP(2 txs)
2022-06-02 13:11:47,013: [87] m.c.plugin:WARNING: Caught will_solve in state None, but failed to capture its initialization
2022-06-02 13:11:47,018: [93] m.c.manticore:INFO: Generated testcase No. 5 - STOP(2 txs)
2022-06-02 13:11:47,020: [93] m.c.plugin:WARNING: Caught will_solve in state None, but failed to capture its initialization
Traceback (most recent call last):
  File "/usr/local/bin/manticore", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/manticore/__main__.py", line 42, in main
    ethereum_main(args, logger)
  File "/usr/local/lib/python3.7/dist-packages/manticore/ethereum/cli.py", line 145, in ethereum_main
    m.finalize(only_alive_states=args.only_alive_testcases)
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/manticore.py", line 177, in newFunction
    return func(self, *args, **kw)
  File "/usr/local/lib/python3.7/dist-packages/manticore/ethereum/manticore.py", line 1811, in finalize
    "{:x}: {:2.2f}%\n".format(int(address), self.global_coverage(address))
  File "/usr/local/lib/python3.7/dist-packages/manticore/ethereum/manticore.py", line 1888, in global_coverage
    runtime_bytecode = state.solve_one(code)
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/state.py", line 483, in solve_one
    return self.solve_one_n(expr, constrain=constrain)[0]
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/state.py", line 494, in solve_one_n
    return self.solve_one_n_batched(exprs, constrain)
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/state.py", line 509, in solve_one_n_batched
    values = self._solver.get_value_in_batch(self._constraints, exprs)
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/smtlib/solver.py", line 745, in get_value_in_batch
    "Solver could not find a value for expression under current constraint set"
manticore.exceptions.SolverError: Solver could not find a value for expression under current constraint set