2023-01-17 17:44:34,673: [11] m.main:INFO: Registered plugins: IntrospectionAPIPlugin, <class 'manticore.ethereum.plugins.SkipRevertBasicBlocks'>, <class 'manticore.ethereum.plugins.FilterFunctions'>
2023-01-17 17:44:34,674: [11] m.main:INFO: Beginning analysis
2023-01-17 17:44:34,692: [11] m.e.manticore:INFO: Starting symbolic create contract
2023-01-17 17:44:37,942: [11] m.e.manticore:INFO: Found a concrete globalsha3 b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00Z\xe2cH`g\xb1\xd8\xcb\xafR\xb2\xdc,\xb6j\xc5u\x03d\x8a\x16\x9e\xb2T\xcb\xfa\x1c-*\xc6D\xfapo\x9b' -> 63571599617315351928906317101110325039599705885585700144423599539475104279829
2023-01-17 17:44:38,891: [11] m.e.manticore:INFO: Starting symbolic transaction: 0
2023-01-17 17:45:20,560: [11] m.c.worker:ERROR: Exception in state 1: ManticoreError('Forking on unfeasible constraint set')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 137, in run
    current_state.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/ethereum/state.py", line 8, in execute
    return self._platform.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 3106, in execute
    self.current_vm.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 1322, in execute
    raise Concretize("Symbolic PC", expression=expression, setstate=setstate, policy="ALL")
manticore.core.state.Concretize

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 158, in run
    m._fork(current_state, exc.expression, exc.policy, exc.setstate, exc.values)
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/manticore.py", line 518, in _fork
    raise ManticoreError("Forking on unfeasible constraint set")
manticore.exceptions.ManticoreError: Forking on unfeasible constraint set
 
2023-01-17 17:45:20,600: [11] m.e.manticore:INFO: 2 alive states, 1 terminated states
2023-01-17 17:45:21,843: [11] m.e.manticore:INFO: Starting symbolic transaction: 1
2023-01-17 17:46:58,010: [11] m.c.worker:ERROR: Exception in state 10: ManticoreError('Forking on unfeasible constraint set')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 137, in run
    current_state.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/ethereum/state.py", line 8, in execute
    return self._platform.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 3106, in execute
    self.current_vm.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 1322, in execute
    raise Concretize("Symbolic PC", expression=expression, setstate=setstate, policy="ALL")
manticore.core.state.Concretize

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 158, in run
    m._fork(current_state, exc.expression, exc.policy, exc.setstate, exc.values)
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/manticore.py", line 518, in _fork
    raise ManticoreError("Forking on unfeasible constraint set")
manticore.exceptions.ManticoreError: Forking on unfeasible constraint set
 
2023-01-17 17:46:58,767: [11] m.c.worker:ERROR: Exception in state 1: ManticoreError('Forking on unfeasible constraint set')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 137, in run
    current_state.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/ethereum/state.py", line 8, in execute
    return self._platform.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 3106, in execute
    self.current_vm.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 1322, in execute
    raise Concretize("Symbolic PC", expression=expression, setstate=setstate, policy="ALL")
manticore.core.state.Concretize

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 158, in run
    m._fork(current_state, exc.expression, exc.policy, exc.setstate, exc.values)
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/manticore.py", line 518, in _fork
    raise ManticoreError("Forking on unfeasible constraint set")
manticore.exceptions.ManticoreError: Forking on unfeasible constraint set
 
2023-01-17 17:46:58,941: [11] m.e.manticore:INFO: 4 alive states, 1 terminated states
2023-01-17 17:47:00,494: [94] m.c.manticore:INFO: Generated testcase No. 0 - STOP(3 txs)
2023-01-17 17:47:00,496: [94] m.c.plugin:WARNING: Caught will_solve in state None, but failed to capture its initialization
2023-01-17 17:47:00,543: [93] m.c.manticore:INFO: Generated testcase No. 1 - STOP(3 txs)
2023-01-17 17:47:00,545: [93] m.c.plugin:WARNING: Caught will_solve in state None, but failed to capture its initialization
2023-01-17 17:47:00,550: [95] m.c.manticore:INFO: Generated testcase No. 2 - STOP(3 txs)
2023-01-17 17:47:00,551: [95] m.c.plugin:WARNING: Caught will_solve in state None, but failed to capture its initialization
2023-01-17 17:47:00,686: [92] m.c.manticore:INFO: Generated testcase No. 3 - STOP(3 txs)
2023-01-17 17:47:00,687: [92] m.c.plugin:WARNING: Caught will_solve in state None, but failed to capture its initialization
2023-01-17 17:47:07,734: [11] m.c.manticore:INFO: Results in /mcore_69kkr7hu
2023-01-17 17:47:07,734: [11] m.c.manticore:INFO: Total time: 105.74972414970398
