2022-06-02 13:11:41,296: [14] m.main:INFO: Registered plugins: IntrospectionAPIPlugin, <class 'manticore.ethereum.plugins.SkipRevertBasicBlocks'>, <class 'manticore.ethereum.plugins.FilterFunctions'>
2022-06-02 13:11:41,296: [14] m.main:INFO: Beginning analysis
2022-06-02 13:11:41,300: [14] m.e.manticore:INFO: Starting symbolic create contract
2022-06-02 13:11:41,882: [14] m.e.manticore:INFO: Starting symbolic transaction: 0
2022-06-02 13:11:42,023: [14] m.e.manticore:INFO: 0 alive states, 2 terminated states
2022-06-02 13:11:42,226: [14] m.c.manticore:INFO: Results in /mcore_s3b7smfz
2022-06-02 13:11:42,227: [14] m.c.manticore:INFO: Total time: 0.3408777713775635
2022-06-02 13:11:43,434: [82] m.main:INFO: Registered plugins: IntrospectionAPIPlugin, <class 'manticore.ethereum.plugins.SkipRevertBasicBlocks'>, <class 'manticore.ethereum.plugins.FilterFunctions'>
2022-06-02 13:11:43,435: [82] m.main:INFO: Beginning analysis
2022-06-02 13:11:43,439: [82] m.e.manticore:INFO: Starting symbolic create contract
2022-06-02 13:11:46,698: [82] m.e.manticore:INFO: Starting symbolic transaction: 0
2022-06-02 13:12:48,490: [82] m.c.worker:ERROR: Exception in state 10: ManticoreError('Forking on unfeasible constraint set')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 137, in run
    current_state.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/ethereum/state.py", line 8, in execute
    return self._platform.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 3106, in execute
    self.current_vm.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 1322, in execute
    raise Concretize("Symbolic PC", expression=expression, setstate=setstate, policy="ALL")
manticore.core.state.Concretize

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 158, in run
    m._fork(current_state, exc.expression, exc.policy, exc.setstate, exc.values)
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/manticore.py", line 518, in _fork
    raise ManticoreError("Forking on unfeasible constraint set")
manticore.exceptions.ManticoreError: Forking on unfeasible constraint set
 
2022-06-02 13:12:56,554: [82] m.e.manticore:INFO: Found a concrete globalsha3 b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01' -> 27376155845717860833342594873357525089589924219251518322086369159840883582034
2022-06-02 13:13:04,231: [82] m.e.manticore:INFO: Found a concrete globalsha3 b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x03' -> 109825747609387604026257694119480052437337487955339004288381632936333863410599
2022-06-02 13:15:36,907: [82] m.e.manticore:INFO: 4 alive states, 1 terminated states
2022-06-02 13:15:38,876: [82] m.e.manticore:INFO: Starting symbolic transaction: 1
2022-06-02 13:20:50,840: [82] m.c.worker:ERROR: Exception in state 3: ManticoreError('Forking on unfeasible constraint set')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 137, in run
    current_state.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/ethereum/state.py", line 8, in execute
    return self._platform.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 3106, in execute
    self.current_vm.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 1322, in execute
    raise Concretize("Symbolic PC", expression=expression, setstate=setstate, policy="ALL")
manticore.core.state.Concretize

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 158, in run
    m._fork(current_state, exc.expression, exc.policy, exc.setstate, exc.values)
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/manticore.py", line 518, in _fork
    raise ManticoreError("Forking on unfeasible constraint set")
manticore.exceptions.ManticoreError: Forking on unfeasible constraint set
 
2022-06-02 13:21:16,756: [82] m.c.worker:ERROR: Exception in state 8: ManticoreError('Forking on unfeasible constraint set')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 137, in run
    current_state.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/ethereum/state.py", line 8, in execute
    return self._platform.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 3106, in execute
    self.current_vm.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 1322, in execute
    raise Concretize("Symbolic PC", expression=expression, setstate=setstate, policy="ALL")
manticore.core.state.Concretize

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 158, in run
    m._fork(current_state, exc.expression, exc.policy, exc.setstate, exc.values)
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/manticore.py", line 518, in _fork
    raise ManticoreError("Forking on unfeasible constraint set")
manticore.exceptions.ManticoreError: Forking on unfeasible constraint set
 
2022-06-02 13:23:05,462: [82] m.c.worker:ERROR: Exception in state 9: ManticoreError('Forking on unfeasible constraint set')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 137, in run
    current_state.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/ethereum/state.py", line 8, in execute
    return self._platform.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 3106, in execute
    self.current_vm.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 1322, in execute
    raise Concretize("Symbolic PC", expression=expression, setstate=setstate, policy="ALL")
manticore.core.state.Concretize

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 158, in run
    m._fork(current_state, exc.expression, exc.policy, exc.setstate, exc.values)
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/manticore.py", line 518, in _fork
    raise ManticoreError("Forking on unfeasible constraint set")
manticore.exceptions.ManticoreError: Forking on unfeasible constraint set
 
2022-06-02 13:25:55,110: [82] m.c.worker:ERROR: Exception in state 4: ManticoreError('Forking on unfeasible constraint set')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 137, in run
    current_state.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/ethereum/state.py", line 8, in execute
    return self._platform.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 3106, in execute
    self.current_vm.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 1322, in execute
    raise Concretize("Symbolic PC", expression=expression, setstate=setstate, policy="ALL")
manticore.core.state.Concretize

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 158, in run
    m._fork(current_state, exc.expression, exc.policy, exc.setstate, exc.values)
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/manticore.py", line 518, in _fork
    raise ManticoreError("Forking on unfeasible constraint set")
manticore.exceptions.ManticoreError: Forking on unfeasible constraint set
 
2022-06-02 13:39:24,727: [82] m.e.manticore:INFO: 16 alive states, 1 terminated states
2022-06-02 13:39:30,123: [179] m.c.plugin:WARNING: Caught will_solve in state None, but failed to capture its initialization
2022-06-02 13:39:30,298: [181] m.c.plugin:WARNING: Caught will_solve in state None, but failed to capture its initialization
2022-06-02 13:39:30,424: [183] m.c.plugin:WARNING: Caught will_solve in state None, but failed to capture its initialization
2022-06-02 13:39:30,435: [182] m.c.plugin:WARNING: Caught will_solve in state None, but failed to capture its initialization
2022-06-02 13:39:32,355: [179] m.c.manticore:INFO: Generated testcase No. 0 - RETURN(3 txs)
2022-06-02 13:39:32,815: [183] m.c.manticore:INFO: Generated testcase No. 1 - RETURN(3 txs)
2022-06-02 13:39:33,003: [182] m.c.manticore:INFO: Generated testcase No. 3 - RETURN(3 txs)
2022-06-02 13:39:33,003: [181] m.c.manticore:INFO: Generated testcase No. 2 - RETURN(3 txs)
2022-06-02 13:39:49,294: [180] m.c.plugin:WARNING: Caught will_solve in state None, but failed to capture its initialization
2022-06-02 13:39:49,353: [173] m.c.plugin:WARNING: Caught will_solve in state None, but failed to capture its initialization
2022-06-02 13:39:50,450: [174] m.c.plugin:WARNING: Caught will_solve in state None, but failed to capture its initialization
2022-06-02 13:39:50,473: [178] m.c.plugin:WARNING: Caught will_solve in state None, but failed to capture its initialization
2022-06-02 13:39:51,750: [182] m.c.manticore:INFO: Generated testcase No. 4 - RETURN(3 txs)
2022-06-02 13:39:52,867: [179] m.c.manticore:INFO: Generated testcase No. 5 - RETURN(3 txs)
2022-06-02 13:39:53,153: [177] m.c.plugin:WARNING: Caught will_solve in state None, but failed to capture its initialization
2022-06-02 13:39:54,175: [183] m.c.manticore:INFO: Generated testcase No. 6 - RETURN(3 txs)
2022-06-02 13:39:55,479: [181] m.c.manticore:INFO: Generated testcase No. 7 - RETURN(3 txs)
2022-06-02 13:40:07,353: [173] m.c.manticore:INFO: Generated testcase No. 8 - RETURN(3 txs)
2022-06-02 13:40:07,761: [174] m.c.manticore:INFO: Generated testcase No. 9 - RETURN(3 txs)
2022-06-02 13:40:07,845: [180] m.c.manticore:INFO: Generated testcase No. 10 - RETURN(3 txs)
2022-06-02 13:40:09,343: [178] m.c.manticore:INFO: Generated testcase No. 11 - RETURN(3 txs)
2022-06-02 13:40:09,772: [175] m.c.plugin:WARNING: Caught will_solve in state None, but failed to capture its initialization
2022-06-02 13:40:10,369: [182] m.c.manticore:INFO: Generated testcase No. 12 - RETURN(3 txs)
2022-06-02 13:40:12,747: [177] m.c.manticore:INFO: Generated testcase No. 13 - RETURN(3 txs)
2022-06-02 13:40:27,828: [175] m.c.manticore:INFO: Generated testcase No. 14 - RETURN(3 txs)
2022-06-02 13:40:38,875: [172] m.c.plugin:WARNING: Caught will_solve in state None, but failed to capture its initialization
2022-06-02 13:41:35,741: [172] m.c.manticore:INFO: Generated testcase No. 15 - RETURN(3 txs)